comment: false
coverage:
  precision: 2
  round: down
  range: "70...95"
  status:
    project:
      default:
        target: 91.5%
        threshold: 0
ignore:
  - "tests"
  - "phykit-runner.py"
  - "setup.py"
  - "phykit/__main__.py"
