from os import path
from setuptools import setup, find_packages

from phykit.version import __version__

here = path.abspath(path.dirname(__file__))

with open(path.join(here, "README.md")) as f:
    long_description = f.read()

CLASSIFIERS = [
    'Operating System :: OS Independent',
    'Intended Audience :: Science/Research',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Topic :: Scientific/Engineering',
]

REQUIRES = [
    "biopython>=1.82",
    "matplotlib>=3.7.0",
    "numpy>=1.24.0",
    "scipy>=1.11.3",
    "scikit-learn>=1.4.2",
    "umap-learn>=0.5.0",
    "tqdm>=4.65.0"
]

setup(
    name="phykit",
    description="",
    long_description=long_description,
    long_description_content_type="text/markdown",
    author="Jacob L. Steenwyk",
    author_email="jlsteenwyk@gmail.com",
    url="https://github.com/jlsteenwyk/phykit",
    packages=find_packages(),
    python_requires=">=3.10",
    classifiers=CLASSIFIERS,
    entry_points={
        "console_scripts": [
            "phykit = phykit.phykit:main",
            "pk_alignment_length = phykit.phykit:alignment_length", # Alignment-based functions
            "pk_aln_len = phykit.phykit:alignment_length",
            "pk_al = phykit.phykit:alignment_length",
            "pk_alignment_length_no_gaps = phykit.phykit:alignment_length_no_gaps",
            "pk_aln_len_no_gaps = phykit.phykit:alignment_length_no_gaps",
            "pk_alng = phykit.phykit:alignment_length_no_gaps",
            "pk_alignment_entropy = phykit.phykit:alignment_entropy",
            "pk_aln_entropy = phykit.phykit:alignment_entropy",
            "pk_entropy = phykit.phykit:alignment_entropy",
            "pk_alignment_recoding = phykit.phykit:alignment_recoding",
            "pk_aln_recoding = phykit.phykit:alignment_recoding",
            "pk_recode = phykit.phykit:alignment_recoding",
            "pk_alignment_outlier_taxa = phykit.phykit:alignment_outlier_taxa",
            "pk_outlier_taxa = phykit.phykit:alignment_outlier_taxa",
            "pk_aot = phykit.phykit:alignment_outlier_taxa",
            "pk_column_score = phykit.phykit:column_score",
            "pk_cs = phykit.phykit:column_score",
            "pk_compositional_bias_per_site = phykit.phykit:compositional_bias_per_site",
            "pk_comp_bias_per_site = phykit.phykit:compositional_bias_per_site",
            "pk_cbps = phykit.phykit:compositional_bias_per_site",
            "pk_composition_per_taxon = phykit.phykit:composition_per_taxon",
            "pk_comp_taxon = phykit.phykit:composition_per_taxon",
            "pk_comp_tax = phykit.phykit:composition_per_taxon",
            "pk_faidx = phykit.phykit:faidx",
            "pk_evolutionary_rate_per_site = phykit.phykit:evolutionary_rate_per_site",
            "pk_evo_rate_per_site = phykit.phykit:evolutionary_rate_per_site",
            "pk_erps = phykit.phykit:evolutionary_rate_per_site",
            "pk_get_entry = phykit.phykit:faidx",
            "pk_ge = phykit.phykit:faidx",
            "pk_gc_content = phykit.phykit:gc_content",
            "pk_gc = phykit.phykit:gc_content",
            "pk_mask_alignment = phykit.phykit:mask_alignment",
            "pk_mask_aln = phykit.phykit:mask_alignment",
            "pk_mask = phykit.phykit:mask_alignment",
            "pk_plot_alignment_qc = phykit.phykit:plot_alignment_qc",
            "pk_plot_qc = phykit.phykit:plot_alignment_qc",
            "pk_paqc = phykit.phykit:plot_alignment_qc",
            "pk_occupancy_per_taxon = phykit.phykit:occupancy_per_taxon",
            "pk_occupancy_taxon = phykit.phykit:occupancy_per_taxon",
            "pk_occ_tax = phykit.phykit:occupancy_per_taxon",
            "pk_pairwise_identity = phykit.phykit:pairwise_identity",
            "pk_pairwise_id = phykit.phykit:pairwise_identity",
            "pk_pi = phykit.phykit:pairwise_identity",
            "pk_identity_matrix = phykit.phykit:identity_matrix",
            "pk_id_matrix = phykit.phykit:identity_matrix",
            "pk_seqid = phykit.phykit:identity_matrix",
            "pk_parsimony_informative_sites = phykit.phykit:parsimony_informative_sites",
            "pk_pis = phykit.phykit:parsimony_informative_sites",
            "pk_relative_composition_variability = phykit.phykit:rcv",
            "pk_rel_comp_var = phykit.phykit:rcv",
            "pk_rcv = phykit.phykit:rcv",
            "pk_relative_composition_variability_taxon = phykit.phykit:rcvt",
            "pk_rel_comp_var_taxon = phykit.phykit:rcvt",
            "pk_rcvt = phykit.phykit:rcvt",
            "pk_rename_fasta_entries = phykit.phykit:rename_fasta_entries",
            "pk_rename_fasta = phykit.phykit:rename_fasta_entries",
            "pk_sum_of_pairs_score = phykit.phykit:sum_of_pairs_score",
            "pk_sops = phykit.phykit:sum_of_pairs_score",
            "pk_sop = phykit.phykit:sum_of_pairs_score",
            "pk_variable_sites = phykit.phykit:variable_sites",
            "pk_vs = phykit.phykit:variable_sites",
            "pk_alignment_subsample = phykit.phykit:alignment_subsample",
            "pk_aln_subsample = phykit.phykit:alignment_subsample",
            "pk_subsample = phykit.phykit:alignment_subsample",
            "pk_dstatistic = phykit.phykit:dstatistic",
            "pk_dstat = phykit.phykit:dstatistic",
            "pk_abba_baba = phykit.phykit:dstatistic",
            "pk_dfoil = phykit.phykit:dfoil",
            "pk_dfoil_test = phykit.phykit:dfoil",
            "pk_ancestral_state_reconstruction = phykit.phykit:ancestral_state_reconstruction", # Tree-based functions
            "pk_parsimony_score = phykit.phykit:parsimony_score",
            "pk_parsimony = phykit.phykit:parsimony_score",
            "pk_pars = phykit.phykit:parsimony_score",
            "pk_character_map = phykit.phykit:character_map",
            "pk_charmap = phykit.phykit:character_map",
            "pk_synapomorphy_map = phykit.phykit:character_map",
            "pk_independent_contrasts = phykit.phykit:independent_contrasts",
            "pk_pic = phykit.phykit:independent_contrasts",
            "pk_phylo_contrasts = phykit.phykit:independent_contrasts",
            "pk_asr = phykit.phykit:ancestral_state_reconstruction",
            "pk_anc_recon = phykit.phykit:ancestral_state_reconstruction",
            "pk_concordance_asr = phykit.phykit:concordance_asr",
            "pk_conc_asr = phykit.phykit:concordance_asr",
            "pk_casr = phykit.phykit:concordance_asr",
            "pk_bipartition_support_stats = phykit.phykit:bipartition_support_stats",
            "pk_bss = phykit.phykit:bipartition_support_stats",
            "pk_branch_length_multiplier = phykit.phykit:branch_length_multiplier",
            "pk_blm = phykit.phykit:branch_length_multiplier",
            "pk_collapse_branches = phykit.phykit:collapse_branches",
            "pk_collapse = phykit.phykit:collapse_branches",
            "pk_cb = phykit.phykit:collapse_branches",
            "pk_covarying_evolutionary_rates = phykit.phykit:covarying_evolutionary_rates",
            "pk_cover = phykit.phykit:covarying_evolutionary_rates",
            "pk_consensus_network = phykit.phykit:consensus_network",
            "pk_consnet = phykit.phykit:consensus_network",
            "pk_splitnet = phykit.phykit:consensus_network",
            "pk_splits_network = phykit.phykit:consensus_network",
            "pk_consensus_tree = phykit.phykit:consensus_tree",
            "pk_consensus = phykit.phykit:consensus_tree",
            "pk_ctree = phykit.phykit:consensus_tree",
            "pk_dvmc = phykit.phykit:dvmc",
            "pk_degree_of_violation_of_a_molecular_clock = phykit.phykit:dvmc",
            "pk_evo_rate = phykit.phykit:evolutionary_rate",
            "pk_evolutionary_rate = phykit.phykit:evolutionary_rate",
            "pk_hidden_paralogy_check = phykit.phykit:hidden_paralogy_check",
            "pk_clan_check = phykit.phykit:hidden_paralogy_check",
            "pk_internal_branch_stats = phykit.phykit:internal_branch_stats",
            "pk_ibs = phykit.phykit:internal_branch_stats",
            "pk_internode_labeler = phykit.phykit:internode_labeler",
            "pk_il = phykit.phykit:internode_labeler",
            "pk_last_common_ancestor_subtree = phykit.phykit:last_common_ancestor_subtree",
            "pk_lca_subtree = phykit.phykit:last_common_ancestor_subtree",
            "pk_lb_score = phykit.phykit:lb_score",
            "pk_long_branch_score = phykit.phykit:lb_score",
            "pk_lbs = phykit.phykit:lb_score",
            "pk_monophyly_check = phykit.phykit:monophyly_check",
            "pk_is_monophyletic = phykit.phykit:monophyly_check",
            "pk_nearest_neighbor_interchange = phykit.phykit:nearest_neighbor_interchange",
            "pk_nni = phykit.phykit:nearest_neighbor_interchange",
            "pk_patristic_distances = phykit.phykit:patristic_distances",
            "pk_pd = phykit.phykit:patristic_distances",
            "pk_phylogenetic_signal = phykit.phykit:phylogenetic_signal",
            "pk_phylo_signal = phykit.phykit:phylogenetic_signal",
            "pk_ps = phykit.phykit:phylogenetic_signal",
            "pk_phylogenetic_ordination = phykit.phykit:phylogenetic_ordination",
            "pk_phylo_ordination = phykit.phykit:phylogenetic_ordination",
            "pk_ordination = phykit.phykit:phylogenetic_ordination",
            "pk_ord = phykit.phykit:phylogenetic_ordination",
            "pk_phylogenetic_pca = phykit.phykit:phylogenetic_ordination",
            "pk_phylo_pca = phykit.phykit:phylogenetic_ordination",
            "pk_phyl_pca = phykit.phykit:phylogenetic_ordination",
            "pk_ppca = phykit.phykit:phylogenetic_ordination",
            "pk_phylogenetic_dimreduce = phykit.phykit:phylogenetic_ordination",
            "pk_phylo_dimreduce = phykit.phykit:phylogenetic_ordination",
            "pk_dimreduce = phykit.phykit:phylogenetic_ordination",
            "pk_pdr = phykit.phykit:phylogenetic_ordination",
            "pk_phylo_heatmap = phykit.phykit:phylo_heatmap",
            "pk_pheatmap = phykit.phykit:phylo_heatmap",
            "pk_ph = phykit.phykit:phylo_heatmap",
            "pk_phylomorphospace = phykit.phykit:phylomorphospace",
            "pk_phylomorpho = phykit.phykit:phylomorphospace",
            "pk_phmo = phykit.phykit:phylomorphospace",
            "pk_phylogenetic_regression = phykit.phykit:phylogenetic_regression",
            "pk_phylo_regression = phykit.phykit:phylogenetic_regression",
            "pk_pgls = phykit.phykit:phylogenetic_regression",
            "pk_phylogenetic_glm = phykit.phykit:phylogenetic_glm",
            "pk_phylo_glm = phykit.phykit:phylogenetic_glm",
            "pk_pglm = phykit.phykit:phylogenetic_glm",
            "pk_phylo_logistic = phykit.phykit:phylo_logistic",
            "pk_phylo_logreg = phykit.phykit:phylo_logistic",
            "pk_plogreg = phykit.phykit:phylo_logistic",
            "pk_stochastic_character_map = phykit.phykit:stochastic_character_map",
            "pk_simmap = phykit.phykit:stochastic_character_map",
            "pk_scm = phykit.phykit:stochastic_character_map",
            "pk_cont_map = phykit.phykit:cont_map",
            "pk_contmap = phykit.phykit:cont_map",
            "pk_cmap = phykit.phykit:cont_map",
            "pk_density_map = phykit.phykit:density_map",
            "pk_densitymap = phykit.phykit:density_map",
            "pk_dmap = phykit.phykit:density_map",
            "pk_phenogram = phykit.phykit:phenogram",
            "pk_traitgram = phykit.phykit:phenogram",
            "pk_tg = phykit.phykit:phenogram",
            "pk_cophylo = phykit.phykit:cophylo",
            "pk_tanglegram = phykit.phykit:cophylo",
            "pk_tangle = phykit.phykit:cophylo",
            "pk_rate_heterogeneity = phykit.phykit:rate_heterogeneity",
            "pk_brownie = phykit.phykit:rate_heterogeneity",
            "pk_rh = phykit.phykit:rate_heterogeneity",
            "pk_fit_continuous = phykit.phykit:fit_continuous",
            "pk_fitcontinuous = phykit.phykit:fit_continuous",
            "pk_fc = phykit.phykit:fit_continuous",
            "pk_fit_discrete = phykit.phykit:fit_discrete",
            "pk_fitdiscrete = phykit.phykit:fit_discrete",
            "pk_fd = phykit.phykit:fit_discrete",
            "pk_ouwie = phykit.phykit:ouwie",
            "pk_fit_ouwie = phykit.phykit:ouwie",
            "pk_multi_regime_ou = phykit.phykit:ouwie",
            "pk_ou_shift_detection = phykit.phykit:ou_shift_detection",
            "pk_ou_shifts = phykit.phykit:ou_shift_detection",
            "pk_l1ou = phykit.phykit:ou_shift_detection",
            "pk_detect_shifts = phykit.phykit:ou_shift_detection",
            "pk_quartet_network = phykit.phykit:quartet_network",
            "pk_quartet_net = phykit.phykit:quartet_network",
            "pk_qnet = phykit.phykit:quartet_network",
            "pk_nanuq = phykit.phykit:quartet_network",
            "pk_quartet_pie = phykit.phykit:quartet_pie",
            "pk_qpie = phykit.phykit:quartet_pie",
            "pk_quartet_pie_chart = phykit.phykit:quartet_pie",
            "pk_ltt = phykit.phykit:ltt",
            "pk_gamma_stat = phykit.phykit:ltt",
            "pk_gamma = phykit.phykit:ltt",
            "pk_network_signal = phykit.phykit:network_signal",
            "pk_netsig = phykit.phykit:network_signal",
            "pk_net_signal = phykit.phykit:network_signal",
            "pk_polytomy_test = phykit.phykit:polytomy_test",
            "pk_polyt_test = phykit.phykit:polytomy_test",
            "pk_ptt = phykit.phykit:polytomy_test",
            "pk_polyt = phykit.phykit:polytomy_test",
            "pk_print_tree = phykit.phykit:print_tree",
            "pk_print = phykit.phykit:print_tree",
            "pk_pt = phykit.phykit:print_tree",
            "pk_prune_tree = phykit.phykit:prune_tree",
            "pk_prune = phykit.phykit:prune_tree",
            "pk_relative_rate_test = phykit.phykit:relative_rate_test",
            "pk_rrt = phykit.phykit:relative_rate_test",
            "pk_tajima_rrt = phykit.phykit:relative_rate_test",
            "pk_threshold_model = phykit.phykit:threshold_model",
            "pk_threshold = phykit.phykit:threshold_model",
            "pk_thresh = phykit.phykit:threshold_model",
            "pk_threshbayes = phykit.phykit:threshold_model",
            "pk_thresh_bayes = phykit.phykit:threshold_model",
            "pk_rename_tree_tips = phykit.phykit:rename_tree_tips",
            "pk_rename_tree = phykit.phykit:rename_tree_tips",
            "pk_rename_tips = phykit.phykit:rename_tree_tips",
            "pk_kf_distance = phykit.phykit:kf_distance",
            "pk_kuhner_felsenstein_distance = phykit.phykit:kf_distance",
            "pk_kf_dist = phykit.phykit:kf_distance",
            "pk_kf = phykit.phykit:kf_distance",
            "pk_rf_distance = phykit.phykit:rf_distance",
            "pk_robinson_foulds_distance = phykit.phykit:rf_distance",
            "pk_rf_dist = phykit.phykit:rf_distance",
            "pk_rf = phykit.phykit:rf_distance",
            "pk_root_tree = phykit.phykit:root_tree",
            "pk_root = phykit.phykit:root_tree",
            "pk_rt = phykit.phykit:root_tree",
            "pk_spurious_sequence = phykit.phykit:spurious_sequence",
            "pk_spurious_seq = phykit.phykit:spurious_sequence",
            "pk_ss = phykit.phykit:spurious_sequence",
            "pk_terminal_branch_stats = phykit.phykit:terminal_branch_stats",
            "pk_tbs = phykit.phykit:terminal_branch_stats",
            "pk_tip_labels = phykit.phykit:tip_labels",
            "pk_labels = phykit.phykit:tip_labels",
            "pk_tree_labels = phykit.phykit:tip_labels",
            "pk_tl = phykit.phykit:tip_labels",
            "pk_tip_to_tip_distance = phykit.phykit:tip_to_tip_distance",
            "pk_t2t_dist = phykit.phykit:tip_to_tip_distance",
            "pk_t2t = phykit.phykit:tip_to_tip_distance",
            "pk_tip_to_tip_node_distance = phykit.phykit:tip_to_tip_node_distance",
            "pk_t2t_node_dist = phykit.phykit:tip_to_tip_node_distance",
            "pk_t2t_nd = phykit.phykit:tip_to_tip_node_distance",
            "pk_total_tree_length = phykit.phykit:total_tree_length",
            "pk_tree_len = phykit.phykit:total_tree_length",
            "pk_treeness = phykit.phykit:treeness",
            "pk_tness = phykit.phykit:treeness",
            "pk_saturation = phykit.phykit:saturation", # Alignment- and tree-based functions
            "pk_sat = phykit.phykit:saturation",
            "pk_treeness_over_rcv = phykit.phykit:treeness_over_rcv",
            "pk_toverr = phykit.phykit:treeness_over_rcv",
            "pk_tor = phykit.phykit:treeness_over_rcv",
            "pk_evo_tempo_map = phykit.phykit:evo_tempo_map",
            "pk_etm = phykit.phykit:evo_tempo_map",
            "pk_discordance_asymmetry = phykit.phykit:discordance_asymmetry",
            "pk_disc_asym = phykit.phykit:discordance_asymmetry",
            "pk_da = phykit.phykit:discordance_asymmetry",
            "pk_spectral_discordance = phykit.phykit:spectral_discordance",
            "pk_spec_disc = phykit.phykit:spectral_discordance",
            "pk_sd = phykit.phykit:spectral_discordance",
            "pk_trait_correlation = phykit.phykit:trait_correlation",
            "pk_trait_corr = phykit.phykit:trait_correlation",
            "pk_phylo_corr = phykit.phykit:trait_correlation",
            "pk_tree_space = phykit.phykit:tree_space",
            "pk_tspace = phykit.phykit:tree_space",
            "pk_tree_landscape = phykit.phykit:tree_space",
            "pk_trait_rate_map = phykit.phykit:trait_rate_map",
            "pk_rate_map = phykit.phykit:trait_rate_map",
            "pk_branch_rates = phykit.phykit:trait_rate_map",
            "pk_create_concatenation_matrix = phykit.phykit:create_concatenation_matrix", # Helper functions
            "pk_create_concat = phykit.phykit:create_concatenation_matrix",
            "pk_cc = phykit.phykit:create_concatenation_matrix",
            "pk_thread_dna = phykit.phykit:thread_dna",
            "pk_pal2nal = phykit.phykit:thread_dna",
            "pk_p2n = phykit.phykit:thread_dna",
        ]
    },
    version=__version__,
    include_package_data=True,
    install_requires=REQUIRES,
)

## push new version to pypi
# rm -rf dist
# python3 setup.py sdist bdist_wheel --universal
# twine upload dist/* -r pypi
# then push to anaconda
#
