import pytest
import sys
from mock import patch, call
from pathlib import Path
from textwrap import dedent

from phykit.phykit import Phykit

here = Path(__file__)


@pytest.mark.integration
class TestDNAThreader(object):
    @patch("builtins.print")
    def test_dna_threader_OG0002774(self, mocked_print):
        expected_result_0 = dedent(
            """>sample8_000590-T1"""
        )
        expected_result_1 = dedent(
            """------------------------------------------------------------------ATGGAGCTTACAGAGGAAGACATCCAACCCCAGATGACTCGAAGACGTCCCGGGCAGAGTGCTCTAACGACGCCTCGAAATGAAAAAGACCGAGTAGAGATCCAGTCTGGAACGGAGTTCGGCATCACCCTGGGTACCCCGATTGGAATGATGGTGCGCAACGAGGATCAGAGACCCAAGGACTACGGTGGCAGCACAATGGATCTCTACCCTCGTCCCAGTCACGCTGATTATACTTACCTGGAGAAATACGGTGTCAAGGCGAGCAGCGGTGGTGGCCGGAGTAGTGCCCGCGAGACCATTGGCCGTGTCGCCGCAGGAGCCATTGCGGAGAAGTACCTACGCCTGTCGCATGGTGTCGAAATTGTCGCCTTTGTGTCCTCCGTTGGTAACGAACACCTTTTCCCGCCGACCCCCGAGCACCCTTCTCCATCGACCAACCCTGAGTTCCTGAAGCTCATCGAGACCATCGACCGTAAGACTGTCGATGCCTTCGTCCCCACTCGCTGCCCGAACGAGGAGGCGGCGGCGCGCATGACAAAAGTGATCGAGACTTTCCGGGACAACCAAGATAGCATCGGCGGCACCGTCACCTGCGTGATCCGCAACGTCCCCGTCGGCCTGGGCGAGCCTTGCTTCGACAAGCTCGAGGCCAAGCTGGCGCACGCCATGCTCAGCATCCCCGCCACCAAGGGCTTTGAGATCGGCTCGGGCTTCGGTGGCTGCGAGGTCCCCGGCTCCATCCACAACGACCCCTTCACCGTCTCCGAGGTCCAGACCCGCACCGGCAGCACACAGCGCCTGACCACCAAGACCAACAACTCCGGCGGCATCCAGGGCGGGATCTCCAACGGCGCTCCCATCTATTTCCGCGTTGCCTTCAAGCCCCCCGCCACCATCGGCCAGGCTCAGACCACCGCCTCTTACAGCTTCGAGGAGGGCATCCTCGAGGCCAAGGGCCGCCACGACCCCTGCGTTACCCCTCGTGCTGTCCCCATCGTCGAGGCCATGTCCGCCCTCGTCGTCATGGATGCGCTCATGGCCCAGTATGCCCGCGAAAGCGCAAAGAATTTACTGCCCCCGCTGCCCAGCACCCTCCCTACCAAACCGACTCTCGGCTCCAGCGGTGCTCCCGCCTCTTCA"""
        )   
        expected_result_2 = dedent(
            """>sample25_002627-T1"""  
        )
        expected_result_3 = dedent(
            """ATGACCACCTATGGTGAATCCCATTGCCGCTCTGTCGGCTGCATCGTCGATGGCTGCCCTCCAGGCATGGAGCTTACAGAGGAAGACATCCAACCCCAGATGACTCGAAGACGTCCCGGGCAGAGTGCTCTAACGACGCCTCGAAATGAAAAAGACCGAGTAGAGATCCAGTCTGGAACGGAGTTCGGCATCACCCTGGGTACCCCGATTGGAATGATGGTGCGCAACGAGGATCAGAGACCCAAGGACTACGGTGGCAGCACAATGGATCTCTACCCTCGTCCCAGTCACGCTGATTATACTTACCTGGAGAAATACGGTGTCAAGGCGAGCAGCGGTGGTGGCCGGAGTAGTGCCCGCGAGACCATTGGCCGTGTCGCCGCAGGAGCCATTGCGGAGAAGTACCTACGCCTGTCGCATGGTGTCGAAATTGTCGCCTTTGTGTCCTCCGTTGGTAACGAACACCTTTTCCCGCCGACCCCCGAGCACCCTTCTCCATCGACCAACCCTGAGTTCCTGAAGCTCATCGAGACCATCGACCGTAAGACTGTCGATGCCTTCGTCCCCACTCGCTGCCCGAACGAGGAGGCGGCGGCACGCATGACAAAAGTGATCGAGACTTTCCGGGACAACCAAGATAGCATCGGCGGCACCGTCACCTGCGTGATCCGCAACGTCCCCGTCGGCCTGGGCGAGCCTTGCTTCGACAAGCTCGAGGCCAAGCTGGCGCACGCCATGCTCAGCATCCCCGCCACCAAGGGCTTTGAGATCGGCTCGGGCTTCGGTGGCTGCGAGGTCCCCGGCTCCATCCACAACGACCCCTTCACCGTCTCCGAGGTCCAGACCCGCACCGGCAGCACACAGCGCCTGACCACCAAGACCAACAACTCCGGCGGCATCCAGGGCGGGATCTCCAACGGCGCTCCCATCTATTTCCGCGTTGCCTTCAAGCCCCCCGCCACCATCGGCCAGGCTCAGACCACCGCCTCTTACAGCTTCGAGGAGGGCATCCTCGAGGCCAAGGGCCGCCACGACCCCTGCGTTACCCCTCGTGCTGTCCCCATCGTCGAGGCCATGTCCGCCCTCGTCGTCATGGATGCGCTCATGGCCCAGTATGCCCGCGAAAGCGCAAAGAATTTACTGCCCCCGCTGCCCAGCACCCTCCCTACCAAACCGACTCTCGGCTCCAGCGGTGCTCCCGCCTCTTCA"""
        )
        testargs = [
            "phykit",
            "thread_dna",
            "-p",
            f"{here.parent.parent.parent}/sample_files/OG0002774.aln.afa.txt",
            "-c",
            f"{here.parent.parent.parent}/sample_files/OG0002774.aln.afa.clipkit.log.txt",
            "-n",
            f"{here.parent.parent.parent}/sample_files/OG0002774.mrna.fa.txt",
        ]

        with patch.object(sys, "argv", testargs):
            Phykit()
        assert mocked_print.mock_calls == [
            call(expected_result_0),
            call(expected_result_1),
            call(expected_result_2),
            call(expected_result_3),
        ]

    @patch("builtins.print")
    def test_dna_threader_OG0002774_alias0(self, mocked_print):
        expected_result_0 = dedent(
            """>sample8_000590-T1"""
        )
        expected_result_1 = dedent(
            """------------------------------------------------------------------ATGGAGCTTACAGAGGAAGACATCCAACCCCAGATGACTCGAAGACGTCCCGGGCAGAGTGCTCTAACGACGCCTCGAAATGAAAAAGACCGAGTAGAGATCCAGTCTGGAACGGAGTTCGGCATCACCCTGGGTACCCCGATTGGAATGATGGTGCGCAACGAGGATCAGAGACCCAAGGACTACGGTGGCAGCACAATGGATCTCTACCCTCGTCCCAGTCACGCTGATTATACTTACCTGGAGAAATACGGTGTCAAGGCGAGCAGCGGTGGTGGCCGGAGTAGTGCCCGCGAGACCATTGGCCGTGTCGCCGCAGGAGCCATTGCGGAGAAGTACCTACGCCTGTCGCATGGTGTCGAAATTGTCGCCTTTGTGTCCTCCGTTGGTAACGAACACCTTTTCCCGCCGACCCCCGAGCACCCTTCTCCATCGACCAACCCTGAGTTCCTGAAGCTCATCGAGACCATCGACCGTAAGACTGTCGATGCCTTCGTCCCCACTCGCTGCCCGAACGAGGAGGCGGCGGCGCGCATGACAAAAGTGATCGAGACTTTCCGGGACAACCAAGATAGCATCGGCGGCACCGTCACCTGCGTGATCCGCAACGTCCCCGTCGGCCTGGGCGAGCCTTGCTTCGACAAGCTCGAGGCCAAGCTGGCGCACGCCATGCTCAGCATCCCCGCCACCAAGGGCTTTGAGATCGGCTCGGGCTTCGGTGGCTGCGAGGTCCCCGGCTCCATCCACAACGACCCCTTCACCGTCTCCGAGGTCCAGACCCGCACCGGCAGCACACAGCGCCTGACCACCAAGACCAACAACTCCGGCGGCATCCAGGGCGGGATCTCCAACGGCGCTCCCATCTATTTCCGCGTTGCCTTCAAGCCCCCCGCCACCATCGGCCAGGCTCAGACCACCGCCTCTTACAGCTTCGAGGAGGGCATCCTCGAGGCCAAGGGCCGCCACGACCCCTGCGTTACCCCTCGTGCTGTCCCCATCGTCGAGGCCATGTCCGCCCTCGTCGTCATGGATGCGCTCATGGCCCAGTATGCCCGCGAAAGCGCAAAGAATTTACTGCCCCCGCTGCCCAGCACCCTCCCTACCAAACCGACTCTCGGCTCCAGCGGTGCTCCCGCCTCTTCA"""
        )   
        expected_result_2 = dedent(
            """>sample25_002627-T1"""  
        )
        expected_result_3 = dedent(
            """ATGACCACCTATGGTGAATCCCATTGCCGCTCTGTCGGCTGCATCGTCGATGGCTGCCCTCCAGGCATGGAGCTTACAGAGGAAGACATCCAACCCCAGATGACTCGAAGACGTCCCGGGCAGAGTGCTCTAACGACGCCTCGAAATGAAAAAGACCGAGTAGAGATCCAGTCTGGAACGGAGTTCGGCATCACCCTGGGTACCCCGATTGGAATGATGGTGCGCAACGAGGATCAGAGACCCAAGGACTACGGTGGCAGCACAATGGATCTCTACCCTCGTCCCAGTCACGCTGATTATACTTACCTGGAGAAATACGGTGTCAAGGCGAGCAGCGGTGGTGGCCGGAGTAGTGCCCGCGAGACCATTGGCCGTGTCGCCGCAGGAGCCATTGCGGAGAAGTACCTACGCCTGTCGCATGGTGTCGAAATTGTCGCCTTTGTGTCCTCCGTTGGTAACGAACACCTTTTCCCGCCGACCCCCGAGCACCCTTCTCCATCGACCAACCCTGAGTTCCTGAAGCTCATCGAGACCATCGACCGTAAGACTGTCGATGCCTTCGTCCCCACTCGCTGCCCGAACGAGGAGGCGGCGGCACGCATGACAAAAGTGATCGAGACTTTCCGGGACAACCAAGATAGCATCGGCGGCACCGTCACCTGCGTGATCCGCAACGTCCCCGTCGGCCTGGGCGAGCCTTGCTTCGACAAGCTCGAGGCCAAGCTGGCGCACGCCATGCTCAGCATCCCCGCCACCAAGGGCTTTGAGATCGGCTCGGGCTTCGGTGGCTGCGAGGTCCCCGGCTCCATCCACAACGACCCCTTCACCGTCTCCGAGGTCCAGACCCGCACCGGCAGCACACAGCGCCTGACCACCAAGACCAACAACTCCGGCGGCATCCAGGGCGGGATCTCCAACGGCGCTCCCATCTATTTCCGCGTTGCCTTCAAGCCCCCCGCCACCATCGGCCAGGCTCAGACCACCGCCTCTTACAGCTTCGAGGAGGGCATCCTCGAGGCCAAGGGCCGCCACGACCCCTGCGTTACCCCTCGTGCTGTCCCCATCGTCGAGGCCATGTCCGCCCTCGTCGTCATGGATGCGCTCATGGCCCAGTATGCCCGCGAAAGCGCAAAGAATTTACTGCCCCCGCTGCCCAGCACCCTCCCTACCAAACCGACTCTCGGCTCCAGCGGTGCTCCCGCCTCTTCA"""
        )
        testargs = [
            "phykit",
            "p2n",
            "-p",
            f"{here.parent.parent.parent}/sample_files/OG0002774.aln.afa.txt",
            "-c",
            f"{here.parent.parent.parent}/sample_files/OG0002774.aln.afa.clipkit.log.txt",
            "-n",
            f"{here.parent.parent.parent}/sample_files/OG0002774.mrna.fa.txt",
        ]

        with patch.object(sys, "argv", testargs):
            Phykit()
        assert mocked_print.mock_calls == [
            call(expected_result_0),
            call(expected_result_1),
            call(expected_result_2),
            call(expected_result_3),
        ]

    @patch("builtins.print")
    def test_dna_threader_OG0002774_alias1(self, mocked_print):
        expected_result_0 = dedent(
            """>sample8_000590-T1"""
        )
        expected_result_1 = dedent(
            """------------------------------------------------------------------ATGGAGCTTACAGAGGAAGACATCCAACCCCAGATGACTCGAAGACGTCCCGGGCAGAGTGCTCTAACGACGCCTCGAAATGAAAAAGACCGAGTAGAGATCCAGTCTGGAACGGAGTTCGGCATCACCCTGGGTACCCCGATTGGAATGATGGTGCGCAACGAGGATCAGAGACCCAAGGACTACGGTGGCAGCACAATGGATCTCTACCCTCGTCCCAGTCACGCTGATTATACTTACCTGGAGAAATACGGTGTCAAGGCGAGCAGCGGTGGTGGCCGGAGTAGTGCCCGCGAGACCATTGGCCGTGTCGCCGCAGGAGCCATTGCGGAGAAGTACCTACGCCTGTCGCATGGTGTCGAAATTGTCGCCTTTGTGTCCTCCGTTGGTAACGAACACCTTTTCCCGCCGACCCCCGAGCACCCTTCTCCATCGACCAACCCTGAGTTCCTGAAGCTCATCGAGACCATCGACCGTAAGACTGTCGATGCCTTCGTCCCCACTCGCTGCCCGAACGAGGAGGCGGCGGCGCGCATGACAAAAGTGATCGAGACTTTCCGGGACAACCAAGATAGCATCGGCGGCACCGTCACCTGCGTGATCCGCAACGTCCCCGTCGGCCTGGGCGAGCCTTGCTTCGACAAGCTCGAGGCCAAGCTGGCGCACGCCATGCTCAGCATCCCCGCCACCAAGGGCTTTGAGATCGGCTCGGGCTTCGGTGGCTGCGAGGTCCCCGGCTCCATCCACAACGACCCCTTCACCGTCTCCGAGGTCCAGACCCGCACCGGCAGCACACAGCGCCTGACCACCAAGACCAACAACTCCGGCGGCATCCAGGGCGGGATCTCCAACGGCGCTCCCATCTATTTCCGCGTTGCCTTCAAGCCCCCCGCCACCATCGGCCAGGCTCAGACCACCGCCTCTTACAGCTTCGAGGAGGGCATCCTCGAGGCCAAGGGCCGCCACGACCCCTGCGTTACCCCTCGTGCTGTCCCCATCGTCGAGGCCATGTCCGCCCTCGTCGTCATGGATGCGCTCATGGCCCAGTATGCCCGCGAAAGCGCAAAGAATTTACTGCCCCCGCTGCCCAGCACCCTCCCTACCAAACCGACTCTCGGCTCCAGCGGTGCTCCCGCCTCTTCA"""
        )   
        expected_result_2 = dedent(
            """>sample25_002627-T1"""  
        )
        expected_result_3 = dedent(
            """ATGACCACCTATGGTGAATCCCATTGCCGCTCTGTCGGCTGCATCGTCGATGGCTGCCCTCCAGGCATGGAGCTTACAGAGGAAGACATCCAACCCCAGATGACTCGAAGACGTCCCGGGCAGAGTGCTCTAACGACGCCTCGAAATGAAAAAGACCGAGTAGAGATCCAGTCTGGAACGGAGTTCGGCATCACCCTGGGTACCCCGATTGGAATGATGGTGCGCAACGAGGATCAGAGACCCAAGGACTACGGTGGCAGCACAATGGATCTCTACCCTCGTCCCAGTCACGCTGATTATACTTACCTGGAGAAATACGGTGTCAAGGCGAGCAGCGGTGGTGGCCGGAGTAGTGCCCGCGAGACCATTGGCCGTGTCGCCGCAGGAGCCATTGCGGAGAAGTACCTACGCCTGTCGCATGGTGTCGAAATTGTCGCCTTTGTGTCCTCCGTTGGTAACGAACACCTTTTCCCGCCGACCCCCGAGCACCCTTCTCCATCGACCAACCCTGAGTTCCTGAAGCTCATCGAGACCATCGACCGTAAGACTGTCGATGCCTTCGTCCCCACTCGCTGCCCGAACGAGGAGGCGGCGGCACGCATGACAAAAGTGATCGAGACTTTCCGGGACAACCAAGATAGCATCGGCGGCACCGTCACCTGCGTGATCCGCAACGTCCCCGTCGGCCTGGGCGAGCCTTGCTTCGACAAGCTCGAGGCCAAGCTGGCGCACGCCATGCTCAGCATCCCCGCCACCAAGGGCTTTGAGATCGGCTCGGGCTTCGGTGGCTGCGAGGTCCCCGGCTCCATCCACAACGACCCCTTCACCGTCTCCGAGGTCCAGACCCGCACCGGCAGCACACAGCGCCTGACCACCAAGACCAACAACTCCGGCGGCATCCAGGGCGGGATCTCCAACGGCGCTCCCATCTATTTCCGCGTTGCCTTCAAGCCCCCCGCCACCATCGGCCAGGCTCAGACCACCGCCTCTTACAGCTTCGAGGAGGGCATCCTCGAGGCCAAGGGCCGCCACGACCCCTGCGTTACCCCTCGTGCTGTCCCCATCGTCGAGGCCATGTCCGCCCTCGTCGTCATGGATGCGCTCATGGCCCAGTATGCCCGCGAAAGCGCAAAGAATTTACTGCCCCCGCTGCCCAGCACCCTCCCTACCAAACCGACTCTCGGCTCCAGCGGTGCTCCCGCCTCTTCA"""
        )
        testargs = [
            "phykit",
            "pal2nal",
            "-p",
            f"{here.parent.parent.parent}/sample_files/OG0002774.aln.afa.txt",
            "-c",
            f"{here.parent.parent.parent}/sample_files/OG0002774.aln.afa.clipkit.log.txt",
            "-n",
            f"{here.parent.parent.parent}/sample_files/OG0002774.mrna.fa.txt",
        ]

        with patch.object(sys, "argv", testargs):
            Phykit()
        assert mocked_print.mock_calls == [
            call(expected_result_0),
            call(expected_result_1),
            call(expected_result_2),
            call(expected_result_3),
        ]

    @patch("builtins.print")
    def test_dna_threader_no_log_file(self, mocked_print):
        expected_result_0 = dedent(
            """>sample8_000590-T1"""
        )
        expected_result_1 = dedent(
            """---------------------------------------------------------------------------------------------ATGGAGCTTACAGAGGAAGACATCCAACCCCAGATGACTCGAAGACGTCCCGGGCAGAGTGCTCTAACGACGCCTCGAAATGAAAAAGACCGAGTAGAGATCCAGTCTGGAACGGAGTTCGGCATCACCCTGGGTACCCCGATTGGAATGATGGTGCGCAACGAGGATCAGAGACCCAAGGACTACGGTGGCAGCACAATGGATCTCTACCCTCGTCCCAGTCACGCTGATTATACTTACCTGGAGAAATACGGTGTCAAGGCGAGCAGCGGTGGTGGCCGGAGTAGTGCCCGCGAGACCATTGGCCGTGTCGCCGCAGGAGCCATTGCGGAGAAGTACCTACGCCTGTCGCATGGTGTCGAAATTGTCGCCTTTGTGTCCTCCGTTGGTAACGAACACCTTTTCCCGCCGACCCCCGAGCACCCTTCTCCATCGACCAACCCTGAGTTCCTGAAGCTCATCGAGACCATCGACCGTAAGACTGTCGATGCCTTCGTCCCCACTCGCTGCCCGAACGAGGAGGCGGCGGCGCGCATGACAAAAGTGATCGAGACTTTCCGGGACAACCAAGATAGCATCGGCGGCACCGTCACCTGCGTGATCCGCAACGTCCCCGTCGGCCTGGGCGAGCCTTGCTTCGACAAGCTCGAGGCCAAGCTGGCGCACGCCATGCTCAGCATCCCCGCCACCAAGGGCTTTGAGATCGGCTCGGGCTTCGGTGGCTGCGAGGTCCCCGGCTCCATCCACAACGACCCCTTCACCGTCTCCGAGGTCCAGACCCGCACCGGCAGCACACAGCGCCTGACCACCAAGACCAACAACTCCGGCGGCATCCAGGGCGGGATCTCCAACGGCGCTCCCATCTATTTCCGCGTTGCCTTCAAGCCCCCCGCCACCATCGGCCAGGCTCAGACCACCGCCTCTTACAGCTTCGAGGAGGGCATCCTCGAGGCCAAGGGCCGCCACGACCCCTGCGTTACCCCTCGTGCTGTCCCCATCGTCGAGGCCATGTCCGCCCTCGTCGTCATGGATGCGCTCATGGCCCAGTATGCCCGCGAAAGCGCAAAGAATTTACTGCCCCCGCTGCCCAGCACCCTCCCTACCAAACCGACTCTCGGCTCCAGCGGTGCTCCCGCCTCTTCA"""
        )   
        expected_result_2 = dedent(
            """>sample25_002627-T1"""  
        )
        expected_result_3 = dedent(
            """ATGTCGACGTGGGGAGAATACTTTCGGGTCACCACCTATGGTGAATCCCATTGCCGCTCTGTCGGCTGCATCGTCGATGGCTGCCCTCCAGGCATGGAGCTTACAGAGGAAGACATCCAACCCCAGATGACTCGAAGACGTCCCGGGCAGAGTGCTCTAACGACGCCTCGAAATGAAAAAGACCGAGTAGAGATCCAGTCTGGAACGGAGTTCGGCATCACCCTGGGTACCCCGATTGGAATGATGGTGCGCAACGAGGATCAGAGACCCAAGGACTACGGTGGCAGCACAATGGATCTCTACCCTCGTCCCAGTCACGCTGATTATACTTACCTGGAGAAATACGGTGTCAAGGCGAGCAGCGGTGGTGGCCGGAGTAGTGCCCGCGAGACCATTGGCCGTGTCGCCGCAGGAGCCATTGCGGAGAAGTACCTACGCCTGTCGCATGGTGTCGAAATTGTCGCCTTTGTGTCCTCCGTTGGTAACGAACACCTTTTCCCGCCGACCCCCGAGCACCCTTCTCCATCGACCAACCCTGAGTTCCTGAAGCTCATCGAGACCATCGACCGTAAGACTGTCGATGCCTTCGTCCCCACTCGCTGCCCGAACGAGGAGGCGGCGGCACGCATGACAAAAGTGATCGAGACTTTCCGGGACAACCAAGATAGCATCGGCGGCACCGTCACCTGCGTGATCCGCAACGTCCCCGTCGGCCTGGGCGAGCCTTGCTTCGACAAGCTCGAGGCCAAGCTGGCGCACGCCATGCTCAGCATCCCCGCCACCAAGGGCTTTGAGATCGGCTCGGGCTTCGGTGGCTGCGAGGTCCCCGGCTCCATCCACAACGACCCCTTCACCGTCTCCGAGGTCCAGACCCGCACCGGCAGCACACAGCGCCTGACCACCAAGACCAACAACTCCGGCGGCATCCAGGGCGGGATCTCCAACGGCGCTCCCATCTATTTCCGCGTTGCCTTCAAGCCCCCCGCCACCATCGGCCAGGCTCAGACCACCGCCTCTTACAGCTTCGAGGAGGGCATCCTCGAGGCCAAGGGCCGCCACGACCCCTGCGTTACCCCTCGTGCTGTCCCCATCGTCGAGGCCATGTCCGCCCTCGTCGTCATGGATGCGCTCATGGCCCAGTATGCCCGCGAAAGCGCAAAGAATTTACTGCCCCCGCTGCCCAGCACCCTCCCTACCAAACCGACTCTCGGCTCCAGCGGTGCTCCCGCCTCTTCA"""
        )
        testargs = [
            "phykit",
            "pal2nal",
            "-p",
            f"{here.parent.parent.parent}/sample_files/OG0002774.aln.afa.txt",
            "-n",
            f"{here.parent.parent.parent}/sample_files/OG0002774.mrna.fa.txt",
        ]

        with patch.object(sys, "argv", testargs):
            Phykit()
        assert mocked_print.mock_calls == [
            call(expected_result_0),
            call(expected_result_1),
            call(expected_result_2),
            call(expected_result_3),
        ]

